---
title: "Projects and Interests"
---

# {.tabset .tabset-fade .tabset-pills}
## Professional projects

###Investigation of sRNAs in parasitic plants
Small regulatory RNAs (sRNAs) are thought to function in *trans*-species regulation between host and parasite/pathogen. Our work examined this system in parasitism by the noxious weed *Cuscuta campestris*, finding numerous micro RNAs (miRNAs) which regulate host mRNAs. Recent work has looked broadly at the *Cuscuta* genus, finding that the parasite produces a broad spectrum of sRNAs which can target host mRNAs. Furthermore, this provides an evolutionary paradigm by which the parasite can maintain targeting in-spite of host adaptation.

* __NR Johnson__, CW dePamphilis, and MJ Axtell. [Compensatory sequence variation between trans-species small RNAs and their target sites](https://www.biorxiv.org/content/10.1101/675900v1), *BioRxiv* (2019) - **Preprint**

* __NR Johnson__, and MJ Axtell. [Small RNA warfare: exploring origins and function of *trans*-species microRNAs from the parasitic plant *Cuscuta*](https://doi.org/10.1016/j.pbi.2019.03.014), *Curr. Opin. Plant Biology* (2019) - **Review**

* S Shahid, G Kim, **NR Johnson**, E Wafula, F Wang, C Coruh, V Bernal-Galeano, T Phifer, CW dePamphilis, JH Westwood, and MJ Axtell. ["MicroRNAs from the parasitic plant Cuscuta campestris target host messenger RNAs"](https://doi.org/10.1038/nature25027). *Nature* (2018) - **Research**<br/><br/>


###Tool development in sRNA-sequencing

Alignment and annotation of sRNA-seq data suffers from high-rates of ambiguously mapping reads. Methods in the field inadequately solved this problem, leading us to implement algorithms for estimating read alignment in our lab's tool: ShortStack. Testing against simulated and real data show that this new method in ShortStack is much more precise in aligning miRNAs and small interfering RNAs than other available methods.

* A Lunardon, __NR Johnson__, E Hagerot, T Phifer, S Polydore, C Coruh, and MJ Axtell. [Integrated annotations and analyses of small RNA-producing loci from 47 diverse plants](https://doi.org/10.1101/756858). *BioRxiv* (2019) -- **Preprint**

* __NR Johnson__, J Yeoh, C Coruh and MJ Axtell. [Improved Placement of Multi-Mapping Small RNAs](https://doi.org/10.1534/g3.116.030452). *G3* (2016) - **Research**<br/><br/>



###The search for xylan synthase in plants

Xylan is one of the most common polymers in the essential cell wall component: hemicellulose, but the molecular machinery directly responsible for its synthesis was unclear. This project detailed phylogenetic analysis of gene families to narrow a search for this protein. Protein expression in *N. benthamiana* and *P. pastoris*, followed by purification and in vitro as well as in vivo assays helped to discover the enzyme essential for xylan backbone synthesis.

* JK Jensen, **NR Johnson** and CG Wilkerson. ["Arabidopsis thaliana IRX10 and two related proteins from psyllium and Physcomitrella patens are xylan xylosyltransferases"](https://doi.org/10.1111/tpj.12641). *The Plant Journal* (2014) - **Research**

* JK Jensen, **NR Johnson** and CG Wilkerson. ["Discovery of diversity in xylan biosynthetic genes by transcriptional profiling of a heteroxylan containing mucilaginous tissue"](https://doi.org/10.3389/fpls.2013.00183). *Front. Plant Sci.* (2013) - **Research**


## Personal projects
*This is a collection of silly diversions, some finished and others incomplete. Links are updated at my leisure, meaning that most are missing...*

* 3d-printing
    * Cuscuta holders
    * Tissue microarray mold (mold)
    * [Tube rack for magnetic bead separation](https://www.thingiverse.com/thing:1132367) (Credit: destroyer2012)
* Home automation
    * Robox - automated catfeeder
    * Bionic bucket - automated plant watering apparatus
    * Humidifier - humidity sensor linked to humidifier utilizing an arduino
* Raspberry Pi fiddlings
    * Photobooth
    * Jeopardy!
* Designs and Construction
    <!-- * [Storage side-table](./projects/storage_side-table.html) -->
    * Storage side-table
    * [Pot-hanger](./projects/pot-hanger.html)

## Scripts and useful links

https://github.com/MikeAxtell <br/>
  Mike Axtell's github page, where you can find **ShortStack** and other useful scripts.

http://axtelldata.bio.psu.edu/data/old_scripts/find_3p_adapter/ <br/>
  Box folder containing a perennially useful script: **find_3p_adapter.pl**. This script can look for a user-supplied common miRNA in untrimmed sRNA-sequencing data to infer what the 3p adapter is. Unbeliveably helpful for when working with publicly available datasets.

https://www.ascb.org/careers/how-to-print-a-fabric-poster/ <br/>
  A guide to printing fabric posters for conferences. The company www.spoonflower.com is the actual service and they do good work. Recently they replaced the **"performance knit"** with **"performance pique"** - not as crisp but still a nice poster.

#




