---
title: "Publications"
output: html_document
---

1. A Lunardon, __NR Johnson__, E Hagerot, T Phifer, S Polydore, C Coruh, and MJ Axtell. [Integrated annotations and analyses of small RNA-producing loci from 47 diverse plants](https://doi.org/10.7554/eLife.49750), *eLife* (2019) -- **Research**

2. __NR Johnson__, CW dePamphilis, and MJ Axtell. [Compensatory sequence variation between trans-species small RNAs and their target sites](https://doi.org/10.1101/675900), *eLife* (2019) - **Research, In Press**

3. __NR Johnson__, and MJ Axtell. [Small RNA warfare: exploring origins and function of *trans*-species microRNAs from the parasitic plant *Cuscuta*](https://doi.org/10.1016/j.pbi.2019.03.014), *Curr. Opin. Plant Biology* (2019) - **Review**
  
4. S Shahid, G Kim, **NR Johnson**, E Wafula, F Wang, C Coruh, V Bernal-Galeano, T Phifer, CW dePamphilis, JH Westwood, MJ Axtell. ["MicroRNAs from the parasitic plant Cuscuta campestris target host messenger RNAs"](https://doi.org/10.1038/nature25027). *Nature* (2018) - **Research**

5. F Wang, **NR Johnson**, C Coruh and MJ Axtell. ["Genome-wide analysis of single non-templated nucleotides in plant endogenous siRNAs and miRNAs"](https://doi.org/10.1093/nar/gkw457). *Nucleic Acids Res.* (2016) - **Research**

6. **NR Johnson**, C Coruh and MJ Axtell. ["Improved Placement of Multi-Mapping Small RNAs"](https://doi.org/10.1534/g3.116.030452). *G3* (2016) - **Research**

7. JK Jensen, **NR Johnson** and CG Wilkerson. ["Arabidopsis thaliana IRX10 and two related proteins from psyllium and Physcomitrella patens are xylan xylosyltransferases"](http://onlinelibrary.wiley.com/doi/10.1111/tpj.12641/full). *The Plant Journal* (2014) - **Research**

8. JK Jensen, **NR Johnson** and CG Wilkerson. ["Discovery of diversity in xylan biosynthetic genes by transcriptional profiling of a heteroxylan containing mucilaginous tissue"](https://www.frontiersin.org/articles/10.3389/fpls.2013.00183/full). *Front. Plant Sci.* (2013) - **Research**


